### ISSUE TITLE
1.9.9.1 Bug - white bar at bottom of screen

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#244]
See screenshot, there's a new very large white area at the bottom of all screens. You can see it here below the submit and above the android navigations.
@Pz1c 

![Screenshot_20221223-115706](https://user-images.githubusercontent.com/78275620/209317489-2147ba1f-55cf-4ba0-804e-3097e06308d8.jpg)

**Comment by Pz1c** [comment]
Interesting
I changed framework version from 6.1 to 6.4 in hope that help improve stability.
But looks like we got a new pack of troubles.
@Prulon please say me your android version

**Comment by Prulon** [comment]
android 10

**Comment by Pz1c** [comment]
should be fixed in 1.9.9.5

**Comment by Prulon** [comment]
@Pz1c  not resolved...

**Comment by Prulon** [comment]
I've just updated the app, and I still see everthing like before, are you sure you merged the code?

**Comment by Pz1c** [comment]
are you sure you got 1.9.9.5?

**Comment by Prulon** [comment]
It's pk now
