### ISSUE TITLE
Hall of Fame - online indicator is not upto date

### ISSUE THREAD

**Issue by Prulon** [Pz1c/WavingHands#310]
Sometimes the online indicator in the HoF is not correct, like I would see a sign even though a user has not been active for a long time.
The expected behavior is that whenever you enter the HoF it will be refreshed

**Comment by Pz1c** [comment]
should be fixed in 2.3.0

**Comment by Prulon** [comment]
Still not updated

**Comment by Pz1c** [comment]
@Prulon please correct me in case I'm wrong
if my remembrance clear we should mark as "online" player that was on site no more that 5 minutes ago?

**Comment by Prulon** [comment]
@Pz1c correct

**Comment by Pz1c** [comment]
hope I found problem (finger crossed)

**Comment by Pz1c** [comment]
should be fixed in 3.2.2

**Comment by Prulon** [comment]
Still not working, also I keep getting Succat as always online

**Comment by Pz1c** [comment]
should be fixed in 2.3.8
